version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./userserver/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  task_storage:
    build:
      context: ./
      dockerfile: ./task_storage/Dockerfile
    restart: unless-stopped
    ports:
      - "8001:8001"
    depends_on:
      - taskdb
  taskdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"